import { defaultFlexboxProps } from './defaults'
import { normalizeFlexbox } from './normalize'
import { createFlexboxViewModel } from './viewModel'

export const flexboxContract = {
  defaultProps: defaultFlexboxProps,
  supportsChildren: true,
  schema: {
    title: 'Flexbox',
    categories: [
      { id: 'presets', label: 'Quick Presets', expanded: true },
      { id: 'layout', label: 'Layout', expanded: true },
      { id: 'alignment', label: 'Alignment (Flexbox)', expanded: true },
      { id: 'responsive', label: 'Responsive / Mobile', expanded: false },
      { id: 'spacing', label: 'Spacing & Sizing', expanded: false },
      { id: 'appearance', label: 'Appearance & Card Styling', expanded: false },
    ],
    properties: {
      preset: {
        type: 'select',
        label: 'Quick Preset',
        default: defaultFlexboxProps.preset,
        options: [
          { value: 'custom', label: 'Custom' },
          { value: 'navbar', label: 'Navbar (Space Between + Center)' },
          { value: 'center-hero', label: 'Center Hero (Column + Center)' },
          { value: 'button-group', label: 'Button Group (Row + Wrap)' },
          { value: 'feature-row', label: 'Feature Row (Icon + Text)' },
        ],
        category: 'Quick Presets',
        description: 'Apply pre-configured layout settings in 1 click',
      },
      direction: {
        type: 'select',
        label: 'Flex Direction (flex-direction)',
        default: defaultFlexboxProps.direction,
        options: [
          { value: 'row', label: 'Row (Horizontal ->)' },
          { value: 'column', label: 'Column (Vertical down)' },
          { value: 'row-reverse', label: 'Row Reverse (<-)' },
          { value: 'column-reverse', label: 'Column Reverse (up)' },
        ],
        category: 'Layout',
        description: 'Main axis direction for flex items',
      },
      wrap: {
        type: 'select',
        label: 'Flex Wrap (flex-wrap)',
        default: defaultFlexboxProps.wrap,
        options: [
          { value: 'nowrap', label: 'No Wrap' },
          { value: 'wrap', label: 'Wrap (Next Line)' },
          { value: 'wrap-reverse', label: 'Wrap Reverse' },
        ],
        category: 'Layout',
        description: 'Control whether items wrap when space runs out',
      },
      justifyContent: {
        type: 'select',
        label: 'Justify Content (justify-content)',
        default: defaultFlexboxProps.justifyContent,
        options: [
          { value: 'flex-start', label: 'Flex Start (Left / Start)' },
          { value: 'center', label: 'Center (Middle)' },
          { value: 'flex-end', label: 'Flex End (Right / End)' },
          { value: 'space-between', label: 'Space Between (Far Edges)' },
          { value: 'space-around', label: 'Space Around' },
          { value: 'space-evenly', label: 'Space Evenly' },
        ],
        category: 'Alignment (Flexbox)',
        description: 'Horizontal alignment along the main axis',
      },
      alignItems: {
        type: 'select',
        label: 'Align Items (align-items)',
        default: defaultFlexboxProps.alignItems,
        options: [
          { value: 'stretch', label: 'Stretch (Full Height)' },
          { value: 'flex-start', label: 'Flex Start (Top)' },
          { value: 'center', label: 'Center (Vertically Centered)' },
          { value: 'flex-end', label: 'Flex End (Bottom)' },
          { value: 'baseline', label: 'Baseline' },
        ],
        category: 'Alignment (Flexbox)',
        description: 'Vertical alignment along the cross axis',
      },
      alignContent: {
        type: 'select',
        label: 'Align Content (align-content)',
        default: defaultFlexboxProps.alignContent,
        options: [
          { value: 'stretch', label: 'Stretch' },
          { value: 'flex-start', label: 'Flex Start (Top)' },
          { value: 'center', label: 'Center' },
          { value: 'flex-end', label: 'Flex End (Bottom)' },
          { value: 'space-between', label: 'Space Between' },
          { value: 'space-around', label: 'Space Around' },
          { value: 'space-evenly', label: 'Space Evenly' },
        ],
        category: 'Alignment (Flexbox)',
        description: 'Alignment of multi-line rows when wrapping is enabled',
      },
      stackOnMobile: {
        type: 'toggle',
        label: 'Stack on Mobile (Auto-Column)',
        default: defaultFlexboxProps.stackOnMobile,
        category: 'Responsive / Mobile',
        description: 'Automatically switch horizontal row to vertical column on small screens',
      },
      directionMobile: {
        type: 'select',
        label: 'Mobile Direction',
        default: defaultFlexboxProps.directionMobile,
        options: [
          { value: 'column', label: 'Column (Top to Bottom)' },
          { value: 'column-reverse', label: 'Column Reverse (Bottom to Top)' },
          { value: 'row', label: 'Keep as Row' },
        ],
        category: 'Responsive / Mobile',
      },
      mobileGap: {
        type: 'text',
        label: 'Mobile Gap',
        default: defaultFlexboxProps.mobileGap,
        category: 'Responsive / Mobile',
        description: 'Gap between items on mobile screens',
      },
      gap: {
        type: 'text',
        label: 'Gap (gap)',
        default: defaultFlexboxProps.gap,
        description: 'Space between all items (e.g. 16px, 24px)',
        category: 'Spacing & Sizing',
      },
      padding: {
        type: 'text',
        label: 'Padding',
        default: defaultFlexboxProps.padding,
        description: 'Inner padding for the container (e.g. 16px, 24px 16px)',
        category: 'Spacing & Sizing',
      },
      width: {
        type: 'text',
        label: 'Width',
        default: defaultFlexboxProps.width,
        description: 'Width of the container (e.g. 100%, auto, 600px)',
        category: 'Spacing & Sizing',
      },
      maxWidth: {
        type: 'text',
        label: 'Max Width',
        default: defaultFlexboxProps.maxWidth,
        description: 'Maximum container width (e.g. 1200px, 800px, none)',
        category: 'Spacing & Sizing',
      },
      minHeight: {
        type: 'text',
        label: 'Min Height',
        default: defaultFlexboxProps.minHeight,
        description: 'Minimum height for the container (e.g. auto, 120px)',
        category: 'Spacing & Sizing',
      },
      borderRadius: {
        type: 'text',
        label: 'Border Radius',
        default: defaultFlexboxProps.borderRadius,
        description: 'Rounded corners (e.g. 8px, 16px, 9999px)',
        category: 'Appearance & Card Styling',
      },
      border: {
        type: 'text',
        label: 'Border',
        default: defaultFlexboxProps.border,
        description: 'Border outline (e.g. 1px solid rgba(255,255,255,0.1))',
        category: 'Appearance & Card Styling',
      },
      shadow: {
        type: 'select',
        label: 'Card Shadow',
        default: defaultFlexboxProps.shadow,
        options: [
          { value: 'none', label: 'None' },
          { value: 'sm', label: 'Small Elevation' },
          { value: 'md', label: 'Medium Card Shadow' },
          { value: 'lg', label: 'Large Floating Shadow' },
          { value: 'xl', label: 'Extra Large Glow/Shadow' },
        ],
        category: 'Appearance & Card Styling',
      },
      backgroundColor: {
        type: 'color',
        label: 'Background Color',
        default: defaultFlexboxProps.backgroundColor,
        description: 'Background color for the container',
        category: 'Appearance & Card Styling',
      },
    },
  },
  normalize: normalizeFlexbox,
  createViewModel: createFlexboxViewModel,
}
