import type { AdvancedList } from './types'

export const defaultAdvancedListProps: AdvancedList = {
  version: 1,
  type: 'advancedlist',
  schemaVersion: 1,
  content: {
    items: [
      {
        id: '1',
        title: 'Lightning Fast',
        description: 'Loads in under 2 seconds',
        visible: true,
        iconType: 'emoji',
        iconEmoji: '⚡',
        iconImage: '',
        iconFontAwesome: 'FaBolt',
        iconNumber: 1,
        order: 1,
      },
      {
        id: '2',
        title: 'Secure Payment',
        description: 'Bank-level security with SSL encryption',
        visible: true,
        iconType: 'emoji',
        iconEmoji: '🔒',
        iconImage: '',
        iconFontAwesome: 'FaLock',
        iconNumber: 2,
        order: 2,
      },
      {
        id: '3',
        title: '24/7 Support',
        description: 'Always available to help you',
        visible: true,
        iconType: 'emoji',
        iconEmoji: '📞',
        iconImage: '',
        iconFontAwesome: 'FaHeadset',
        iconNumber: 3,
        order: 3,
      },
    ],
    listType: 'icon',
  },
  responsive: {
    desktop: {},
    tablet: {},
    mobile: {},
  },
  items: [
    {
      id: '1',
      title: 'Lightning Fast',
      description: 'Loads in under 2 seconds',
      visible: true,
      iconType: 'emoji',
      iconEmoji: '⚡',
      iconImage: '',
      iconFontAwesome: 'FaBolt',
      iconNumber: 1,
      order: 1,
    },
    {
      id: '2',
      title: 'Secure Payment',
      description: 'Bank-level security with SSL encryption',
      visible: true,
      iconType: 'emoji',
      iconEmoji: '🔒',
      iconImage: '',
      iconFontAwesome: 'FaLock',
      iconNumber: 2,
      order: 2,
    },
    {
      id: '3',
      title: '24/7 Support',
      description: 'Always available to help you',
      visible: true,
      iconType: 'emoji',
      iconEmoji: '📞',
      iconImage: '',
      iconFontAwesome: 'FaHeadset',
      iconNumber: 3,
      order: 3,
    },
  ],
  listType: 'icon',
  style: {
    columns: 1,
    itemSpacing: '16px',
    gap: '24px',
    padding: '0px',
    margin: '0px',
    alignment: 'left',
    displayStyle: 'plain',
    defaultIcon: '●',
    iconSize: '24px',
    iconPosition: 'left',
    autoNumbering: true,
    titleFontSize: '18px',
    titleFontWeight: '600',
    descriptionFontSize: '14px',
    fontFamily: 'system-ui, sans-serif',
    lineHeight: '1.5',
    titleColor: '#1f2937',
    descriptionColor: '#4b5563',
    iconColor: '#3b82f6',
    backgroundColor: 'transparent',
    border: 'none',
    borderRadius: '8px',
    itemBackground: 'transparent',
    itemPadding: '12px',
    boxShadow: 'none',
    boxHoverShadow: '0 8px 24px rgba(0,0,0,0.12)',
    boxBorderWidth: '1px',
    boxBorderColor: '#e5e7eb',
    fullBoxShadow: 'md',
    fullBoxPadding: '24px',
    fullBoxBackground: '#ffffff',
    fullBoxBorder: '1px solid #e5e7eb',
    fullBoxBorderRadius: '12px',
  },
}
