import type { AdvancedParagraph } from './types'

export const defaultAdvancedParagraphProps: AdvancedParagraph = {
  type: 'advancedparagraph',
  schemaVersion: 1,
  content: {
    text: '<p>Paragraph text...</p>',
  },
  layout: {
    alignment: 'left',
  },
  style: {
    color: 'var(--canvas-muted, #333333)',
    fontSize: '16px',
    fontWeight: 'normal',
    fontFamily: 'inherit',
    lineHeight: '1.6',
    lineHeightMobile: '',
    letterSpacing: 'normal',
    maxWidth: '100%',
    backgroundColor: 'transparent',
    margin: '0 0 16px 0',
    padding: '0',
    width: '100%',
    minHeight: 'auto',
    display: 'block',
    border: 'none',
    borderRadius: '0px',
    borderColor: 'transparent',
    textShadow: 'none',
    boxShadow: 'none',
    opacity: 1,
    fontSizeMobile: '',
    fontSizeTablet: '',
    textAlignMobile: 'left',
    textAlignTablet: 'left',
    textTransform: 'none',
    textDecoration: 'none',
    fontStyle: 'normal',
    transition: 'all 0.2s ease',
  },
  interaction: {
    hover: {
      effect: 'none',
      color: 'var(--canvas-accent2, #0056b3)',
      backgroundColor: 'transparent',
    },
  },
  aria: {
    visible: true,
    ariaLabel: '',
    role: 'paragraph',
    tabIndex: 0,
    className: '',
    customId: '',
    selectable: true,
    editable: true,
    truncate: false,
    maxLines: undefined,
    enableRichText: true,
    allowedFormats: ['bold', 'italic', 'underline', 'color'],
    componentId: '',
  },
  meta: {
    migratedFrom: 'structured',
  },
}
