import type { ButtonProps } from './types'

export const defaultButtonProps: ButtonProps = {
  text: 'Click Me',
  link: '#',
  openInNewTab: false,
  variant: 'primary',
  size: 'medium',
  primaryColor: '#7C6DFA',
  backgroundColor: '#7C6DFA',
  textColor: '#FFFFFF',
  hoverColor: '#A594FF',
  activeColor: '#6A5AE5',
  borderColor: '#7C6DFA',
  useGradient: false,
  gradientColors: '#7f00ff, #e100ff',
  gradientDirection: '135deg',
  gradientType: 'linear',
  borderRadius: '8px',
  borderWidth: '2px',
  shadow: 'md',
  alignment: 'left',
  fullWidth: false,
  width: 'auto',
  marginTop: '0px',
  marginRight: '0px',
  marginBottom: '0px',
  marginLeft: '0px',
  paddingTop: '14px',
  paddingRight: '28px',
  paddingBottom: '14px',
  paddingLeft: '28px',
  fontFamily: "'DM Sans', system-ui, sans-serif",
  fontSize: '16px',
  fontWeight: '600',
  letterSpacing: '0px',
  textTransform: 'none',
  lineHeight: '1.5',
  icon: '',
  iconPosition: 'left',
  iconSize: '16px',
  iconSpacing: '8px',
  disabled: false,
  loading: false,
  loadingText: 'Loading...',
  hoverEffect: 'scale',
  hoverScale: 1.05,
  hoverShadow: 'lg',
  animationType: 'none',
  animationDuration: '0.3s',
  className: '',
  customClass: '',
  customId: '',
  ariaLabel: '',
  onClick: '',
  dataTracking: '',
  mobileSize: 'medium',
  mobileFullWidth: false,
  hideOnMobile: false,
}
