import { defaultButtonProps } from './defaults'
import { normalizeButton } from './normalize'
import { createButtonViewModel } from './viewModel'

export type {
  ButtonAlignment,
  ButtonAnimationType,
  ButtonGradientType,
  ButtonHoverEffect,
  ButtonProps,
  ButtonShadow,
  ButtonSize,
  ButtonVariant,
  ButtonViewModel,
  CanonicalButtonContent,
  CanonicalButtonStyle,
  CanonicalButtonResponsive,
  CanonicalButtonProps,
} from './types'

export const buttonContract = {
  defaultProps: defaultButtonProps,
  schema: {
    title: 'Button',
    categories: [
      { id: 'content', label: 'Content', expanded: true },
      { id: 'style', label: 'Style', expanded: false },
      { id: 'layout', label: 'Layout', expanded: false },
      { id: 'typography', label: 'Typography', expanded: false },
      { id: 'icon', label: 'Icon', expanded: false },
      { id: 'behavior', label: 'Behavior', expanded: false },
      { id: 'advanced', label: 'Advanced', expanded: false },
      { id: 'responsive', label: 'Responsive', expanded: false },
    ],
    properties: {
      text: { type: 'text', label: 'Button Text', default: 'Click Me', category: 'Content' },
      link: { type: 'text', label: 'Link URL', default: '#', category: 'Content' },
      openInNewTab: { type: 'toggle', label: 'Open in New Tab', default: false, category: 'Content' },
      loadingText: { type: 'text', label: 'Loading Text', default: defaultButtonProps.loadingText, category: 'Content' },
      variant: {
        type: 'select',
        label: 'Variant',
        default: defaultButtonProps.variant,
        options: [
          { value: 'primary', label: 'Primary' },
          { value: 'secondary', label: 'Secondary' },
          { value: 'outline', label: 'Outline' },
          { value: 'ghost', label: 'Ghost' },
          { value: 'danger', label: 'Danger' },
          { value: 'success', label: 'Success' },
          { value: 'warning', label: 'Warning' },
        ],
        category: 'Style',
      },
      size: {
        type: 'select',
        label: 'Size',
        default: defaultButtonProps.size,
        options: [
          { value: 'small', label: 'Small' },
          { value: 'medium', label: 'Medium' },
          { value: 'large', label: 'Large' },
        ],
        category: 'Style',
      },
      useGradient: { type: 'toggle', label: 'Use Gradient', default: defaultButtonProps.useGradient, category: 'Style' },
      gradientColors: { type: 'text', label: 'Gradient Colors', default: defaultButtonProps.gradientColors, category: 'Style' },
      gradientDirection: { type: 'text', label: 'Gradient Direction', default: defaultButtonProps.gradientDirection, category: 'Style' },
      gradientType: {
        type: 'select',
        label: 'Gradient Type',
        default: defaultButtonProps.gradientType,
        options: [
          { value: 'linear', label: 'Linear' },
          { value: 'radial', label: 'Radial' },
        ],
        category: 'Style',
      },
      primaryColor: { type: 'color', label: 'Primary Color', default: defaultButtonProps.primaryColor, category: 'Style' },
      alignment: {
        type: 'select',
        label: 'Alignment',
        default: defaultButtonProps.alignment,
        options: [
          { value: 'left', label: 'Left' },
          { value: 'center', label: 'Center' },
          { value: 'right', label: 'Right' },
        ],
        category: 'Layout',
      },
      fullWidth: { type: 'toggle', label: 'Full Width', default: defaultButtonProps.fullWidth, category: 'Layout' },
      width: { type: 'text', label: 'Custom Width', default: defaultButtonProps.width, category: 'Layout', showIf: (props: any) => !props?.fullWidth },
      margin: { type: 'text', label: 'Margin', default: defaultButtonProps.margin, category: 'Layout' },
      padding: { type: 'text', label: 'Padding', default: defaultButtonProps.padding, category: 'Layout' },
      fontFamily: { type: 'text', label: 'Font Family', default: defaultButtonProps.fontFamily, category: 'Typography' },
      fontSize: { type: 'text', label: 'Font Size', default: defaultButtonProps.fontSize, category: 'Typography' },
      fontWeight: { type: 'text', label: 'Font Weight', default: defaultButtonProps.fontWeight, category: 'Typography' },
      letterSpacing: { type: 'text', label: 'Letter Spacing', default: defaultButtonProps.letterSpacing, category: 'Typography' },
      textTransform: {
        type: 'select',
        label: 'Text Transform',
        default: defaultButtonProps.textTransform,
        options: [
          { value: 'none', label: 'None' },
          { value: 'uppercase', label: 'Uppercase' },
          { value: 'lowercase', label: 'Lowercase' },
          { value: 'capitalize', label: 'Capitalize' },
        ],
        category: 'Typography',
      },
      lineHeight: { type: 'text', label: 'Line Height', default: defaultButtonProps.lineHeight, category: 'Typography' },
      borderRadius: { type: 'text', label: 'Border Radius', default: defaultButtonProps.borderRadius, category: 'Style' },
      borderWidth: { type: 'text', label: 'Border Width', default: defaultButtonProps.borderWidth, category: 'Style' },
      backgroundColor: { type: 'color', label: 'Background Color', default: defaultButtonProps.backgroundColor, category: 'Style' },
      textColor: { type: 'color', label: 'Text Color', default: defaultButtonProps.textColor, category: 'Style' },
      hoverColor: { type: 'color', label: 'Hover Color', default: defaultButtonProps.hoverColor, category: 'Style' },
      activeColor: { type: 'color', label: 'Active Color', default: defaultButtonProps.activeColor, category: 'Style' },
      borderColor: { type: 'color', label: 'Border Color', default: defaultButtonProps.borderColor, category: 'Style' },
      shadow: {
        type: 'select',
        label: 'Shadow',
        default: defaultButtonProps.shadow,
        options: ['none', 'sm', 'md', 'lg', 'xl'],
        category: 'Style',
      },
      icon: { type: 'text', label: 'Icon', default: defaultButtonProps.icon, category: 'Icon' },
      iconPosition: {
        type: 'select',
        label: 'Icon Position',
        default: defaultButtonProps.iconPosition,
        options: [
          { value: 'left', label: 'Left' },
          { value: 'right', label: 'Right' },
        ],
        category: 'Icon',
      },
      iconSize: { type: 'text', label: 'Icon Size', default: defaultButtonProps.iconSize, category: 'Icon' },
      iconSpacing: { type: 'text', label: 'Icon Spacing', default: defaultButtonProps.iconSpacing, category: 'Icon' },
      disabled: { type: 'toggle', label: 'Disabled', default: defaultButtonProps.disabled, category: 'Behavior' },
      loading: { type: 'toggle', label: 'Loading', default: defaultButtonProps.loading, category: 'Behavior' },
      hoverEffect: {
        type: 'select',
        label: 'Hover Effect',
        default: defaultButtonProps.hoverEffect,
        options: [
          { value: 'none', label: 'None' },
          { value: 'scale', label: 'Scale' },
          { value: 'lift', label: 'Lift' },
          { value: 'glow', label: 'Glow' },
          { value: 'color-shift', label: 'Color Shift' },
        ],
        category: 'Behavior',
      },
      hoverScale: { type: 'number', label: 'Hover Scale', default: defaultButtonProps.hoverScale, min: 1, max: 1.3, step: 0.01, category: 'Behavior' },
      hoverShadow: { type: 'select', label: 'Hover Shadow', default: defaultButtonProps.hoverShadow, options: ['none', 'sm', 'md', 'lg', 'xl'], category: 'Behavior' },
      animationType: {
        type: 'select',
        label: 'Animation',
        default: defaultButtonProps.animationType,
        options: [
          { value: 'none', label: 'None' },
          { value: 'pulse', label: 'Pulse' },
          { value: 'bounce', label: 'Bounce' },
          { value: 'fade-in', label: 'Fade In' },
        ],
        category: 'Behavior',
      },
      animationDuration: { type: 'text', label: 'Animation Duration', default: defaultButtonProps.animationDuration, category: 'Behavior' },
      className: { type: 'text', label: 'CSS Class', default: defaultButtonProps.className, category: 'Advanced' },
      customId: { type: 'text', label: 'Custom ID', default: defaultButtonProps.customId, category: 'Advanced' },
      ariaLabel: { type: 'text', label: 'ARIA Label', default: defaultButtonProps.ariaLabel, category: 'Advanced' },
      onClick: { type: 'text', label: 'On Click Handler', default: defaultButtonProps.onClick, category: 'Advanced' },
      dataTracking: { type: 'text', label: 'Tracking Data', default: defaultButtonProps.dataTracking, category: 'Advanced' },
      mobileSize: {
        type: 'select',
        label: 'Mobile Size',
        default: defaultButtonProps.mobileSize,
        options: [
          { value: 'small', label: 'Small' },
          { value: 'medium', label: 'Medium' },
          { value: 'large', label: 'Large' },
        ],
        category: 'Responsive',
      },
      mobileFullWidth: { type: 'toggle', label: 'Mobile Full Width', default: defaultButtonProps.mobileFullWidth, category: 'Responsive' },
      hideOnMobile: { type: 'toggle', label: 'Hide On Mobile', default: defaultButtonProps.hideOnMobile, category: 'Responsive' },
    },
  },
  normalize: normalizeButton,
  createViewModel: createButtonViewModel,
}
