import { defaultAdvancedHeadingProps } from './defaults'
import { normalizeAdvancedHeading } from './normalize'
import { createAdvancedHeadingViewModel } from './viewModel'

export type {
  AdvancedHeading,
  AdvancedHeadingAlignment,
  AdvancedHeadingAriaGroup,
  AdvancedHeadingFontStyle,
  AdvancedHeadingHighlightGroup,
  AdvancedHeadingHtmlTag,
  AdvancedHeadingInput,
  AdvancedHeadingLevel,
  AdvancedHeadingMeta,
  AdvancedHeadingSeoGroup,
  AdvancedHeadingStyleGroup,
  AdvancedHeadingTextDecoration,
  AdvancedHeadingTextTransform,
  AdvancedHeadingType,
  AdvancedHeadingViewModel,
} from './types'

export { createAdvancedHeadingViewModel } from './viewModel'

export const advancedHeadingContract = {
  defaultProps: defaultAdvancedHeadingProps,
  schema: {
    title: 'Advanced Heading',
    categories: [
      { id: 'base', label: 'Base', expanded: true },
      { id: 'style', label: 'Style', expanded: false },
      { id: 'highlight', label: 'Highlight', expanded: false },
      { id: 'seo', label: 'SEO', expanded: false },
      { id: 'aria', label: 'ARIA', expanded: false },
    ],
    properties: {
      text: {
        type: 'richtext',
        label: 'Heading Text',
        default: defaultAdvancedHeadingProps.text,
        description: 'Main heading content',
        category: 'Base',
        seoMaxLength: defaultAdvancedHeadingProps.seo.maxLength,
      },
      level: {
        type: 'select',
        label: 'Heading Level',
        default: defaultAdvancedHeadingProps.level,
        options: [
          { value: 'h1', label: 'Heading 1' },
          { value: 'h2', label: 'Heading 2' },
          { value: 'h3', label: 'Heading 3' },
          { value: 'h4', label: 'Heading 4' },
          { value: 'h5', label: 'Heading 5' },
          { value: 'h6', label: 'Heading 6' },
        ],
        category: 'Base',
      },
      usePresetStyles: {
        type: 'toggle',
        label: 'Use Preset Styles',
        default: defaultAdvancedHeadingProps.style.usePresetStyles,
        description: 'Apply the default design system preset for the selected heading level.',
        category: 'Style',
      },
      fontFamily: {
        type: 'select',
        label: 'Font Family',
        default: defaultAdvancedHeadingProps.style.fontFamily,
        options: [
          { value: "'DM Sans', system-ui, sans-serif", label: 'DM Sans' },
          { value: 'system-ui, sans-serif', label: 'System Default' },
          { value: 'Inter, sans-serif', label: 'Inter' },
          { value: 'Roboto, sans-serif', label: 'Roboto' },
          { value: 'Georgia, serif', label: 'Georgia' },
        ],
        category: 'Style',
      },
      fontSize: { type: 'text', label: 'Font Size', default: defaultAdvancedHeadingProps.style.fontSize, category: 'Style' },
      fontWeight: { type: 'text', label: 'Font Weight', default: defaultAdvancedHeadingProps.style.fontWeight, category: 'Style' },
      lineHeight: { type: 'text', label: 'Line Height', default: defaultAdvancedHeadingProps.style.lineHeight, category: 'Style' },
      letterSpacing: { type: 'text', label: 'Letter Spacing', default: defaultAdvancedHeadingProps.style.letterSpacing, category: 'Style' },
      textTransform: {
        type: 'select',
        label: 'Text Transform',
        default: defaultAdvancedHeadingProps.style.textTransform,
        options: [
          { value: 'none', label: 'None' },
          { value: 'uppercase', label: 'Uppercase' },
          { value: 'lowercase', label: 'Lowercase' },
          { value: 'capitalize', label: 'Capitalize' },
        ],
        category: 'Style',
      },
      textDecoration: {
        type: 'select',
        label: 'Text Decoration',
        default: defaultAdvancedHeadingProps.style.textDecoration,
        options: [
          { value: 'none', label: 'None' },
          { value: 'underline', label: 'Underline' },
          { value: 'line-through', label: 'Line Through' },
          { value: 'overline', label: 'Overline' },
        ],
        category: 'Style',
      },
      fontStyle: {
        type: 'select',
        label: 'Font Style',
        default: defaultAdvancedHeadingProps.style.fontStyle,
        options: [
          { value: 'normal', label: 'Normal' },
          { value: 'italic', label: 'Italic' },
          { value: 'oblique', label: 'Oblique' },
        ],
        category: 'Style',
      },
      color: { type: 'color', label: 'Text Color', default: defaultAdvancedHeadingProps.style.color, category: 'Style' },
      hoverColor: { type: 'color', label: 'Hover Color', default: defaultAdvancedHeadingProps.style.hoverColor, category: 'Style' },
      alignment: {
        type: 'select',
        label: 'Alignment',
        default: defaultAdvancedHeadingProps.style.alignment,
        options: [
          { value: 'left', label: 'Left' },
          { value: 'center', label: 'Center' },
          { value: 'right', label: 'Right' },
          { value: 'justify', label: 'Justify' },
        ],
        category: 'Style',
      },
      maxWidth: { type: 'text', label: 'Max Width', default: defaultAdvancedHeadingProps.style.maxWidth, category: 'Style' },
      margin: { type: 'text', label: 'Margin', default: defaultAdvancedHeadingProps.style.margin, category: 'Style' },
      padding: { type: 'text', label: 'Padding', default: defaultAdvancedHeadingProps.style.padding, category: 'Style' },
      highlightText: {
        type: 'text',
        label: 'Highlight Text',
        default: defaultAdvancedHeadingProps.highlight.text,
        category: 'Highlight',
      },
      highlightColor: {
        type: 'color',
        label: 'Highlight Color',
        default: defaultAdvancedHeadingProps.highlight.color,
        category: 'Highlight',
      },
      enableSeoChecks: {
        type: 'toggle',
        label: 'Enable SEO Checks',
        default: defaultAdvancedHeadingProps.seo.enabled,
        category: 'SEO',
      },
      seoMaxLength: {
        type: 'number',
        label: 'SEO Max Length',
        default: defaultAdvancedHeadingProps.seo.maxLength,
        min: 1,
        max: 200,
        category: 'SEO',
      },
      ariaLevel: {
        type: 'number',
        label: 'ARIA Level',
        default: defaultAdvancedHeadingProps.aria.ariaLevel,
        min: 1,
        max: 6,
        category: 'ARIA',
      },
      ariaLabel: {
        type: 'text',
        label: 'ARIA Label',
        default: defaultAdvancedHeadingProps.aria.ariaLabel,
        category: 'ARIA',
      },
      role: {
        type: 'select',
        label: 'Role',
        default: defaultAdvancedHeadingProps.aria.role,
        options: [
          { value: 'heading', label: 'Heading' },
          { value: 'presentation', label: 'Presentation' },
          { value: 'none', label: 'None' },
        ],
        category: 'ARIA',
      },
      autoId: {
        type: 'toggle',
        label: 'Auto-generate ID',
        default: defaultAdvancedHeadingProps.aria.autoId,
        category: 'ARIA',
      },
      customId: { type: 'text', label: 'Custom ID', default: defaultAdvancedHeadingProps.aria.customId, category: 'ARIA' },
      className: { type: 'text', label: 'CSS Class', default: defaultAdvancedHeadingProps.aria.className, category: 'ARIA' },
      dataTracking: { type: 'text', label: 'Tracking Data', default: defaultAdvancedHeadingProps.aria.dataTracking, category: 'ARIA' },
      visible: { type: 'toggle', label: 'Visible', default: defaultAdvancedHeadingProps.aria.visible, category: 'ARIA' },
      componentId: { type: 'text', label: 'Component ID', default: defaultAdvancedHeadingProps.aria.componentId, category: 'ARIA' },
    },
  },
  normalize: normalizeAdvancedHeading,
  createViewModel: createAdvancedHeadingViewModel,
}
