import type { SwiperContainerProps, SwiperSlideItem } from './types'

const PREVIEW_GRADIENTS = [
  'linear-gradient(135deg, #1a1628, #22263a)',
  'linear-gradient(135deg, #0f1a14, #1a2820)',
  'linear-gradient(135deg, #1a1210, #2a1c1a)',
] as const

export const createDefaultSlide = (id: string, slideIndex = 0): SwiperSlideItem => ({
  id,
  components: [],
  bgType: 'gradient',
  bgColor: '#13161e',
  bgImage: '',
  bgGradient: PREVIEW_GRADIENTS[slideIndex % PREVIEW_GRADIENTS.length],
  bgOverlay: false,
  bgOverlayColor: '#000000',
  bgOverlayOpacity: 0.4,
  padding: '12px',
  minHeight: '120px',
  title: '',
  subtitle: '',
})

export const defaultSwiperContainerProps: SwiperContainerProps = {
  version: 1,
  slidesPerView: 3,
  slidesPerGroup: 1,
  spaceBetween: 12,
  direction: 'horizontal',
  centeredSlides: false,
  autoplay: false,
  autoplayDelay: 3000,
  loop: true,
  speed: 500,
  draggable: true,
  grabCursor: true,
  freeMode: false,
  mousewheel: false,
  keyboard: true,
  navigation: true,
  arrowStyle: 'rounded',
  arrowPosition: 'sides',
  pagination: true,
  paginationType: 'bullets',
  paginationDynamic: false,
  paginationClickable: true,
  effect: 'slide',
  effectFadeCrossFade: true,
  effectCubeShadow: true,
  effectCubeSlideShadows: true,
  effectCoverflowRotate: 30,
  effectCoverflowDepth: 100,
  effectCoverflowStretch: 0,
  effectCoverflowModifier: 1,
  effectFlipSlideShadows: true,
  effectCardsPerSlideOffset: 8,
  effectCardsRotate: true,
  hoverEffects: true,
  hoverEffectType: 'none',
  hoverIntensity: 1.06,
  scrollbar: false,
  scrollbarDraggable: true,
  backgroundColor: 'transparent',
  padding: '0px',
  borderRadius: '0px',
  parallax: false,
  parallaxBackground: '',
  height: 'auto',
  width: '100%',
  slideWidth: '300px',
  slideMinHeight: '120px',
  slides: [
    createDefaultSlide('slide-1', 0),
    createDefaultSlide('slide-2', 1),
    createDefaultSlide('slide-3', 2),
    createDefaultSlide('slide-4', 3),
    createDefaultSlide('slide-5', 4),
  ],
}
