import type { ImageProps } from './types'

export const defaultImageProps: ImageProps = {
  src: '',
  alt: 'Image',
  linkUrl: '',
  openInNewTab: false,
  objectFit: 'contain',
  objectPosition: 'center',
  borderRadius: '0px',
  shape: 'default',
  customShape: '',
  showGradientBorder: false,
  gradientBorderColors: '#7f00ff, #00dbde, #7f00ff',
  gradientBorderDirection: '135deg',
  gradientBorderWidth: '10px',
  gradientBorderType: 'conic',
  shadow: 'none',
  width: '100%',
  height: 'auto',
  maxWidth: '100%',
  maxHeight: 'none',
  alignment: 'center',
  componentPositionX: '0px',
  componentPositionY: '0px',
  imageZoom: 1,
  caption: '',
  captionPosition: 'bottom',
  captionAlignment: 'center',
  showOverlay: false,
  overlayColor: '#000000',
  overlayOpacity: 0.3,
  overlayText: '',
  hoverEffect: 'none',
  hoverZoom: 1.1,
  hoverBrightness: 1.2,
  hoverDuration: 0.3,
  filter: 'none',
  lazyLoad: false,
  showLightbox: false,
  className: '',
  customId: '',
  margin: '0px',
  padding: '0px',
  border: 'none',
}
