import { defaultImageProps } from './defaults'
import { normalizeImage } from './normalize'
import { createImageViewModel } from './viewModel'

export type {
  CanonicalImageContent,
  CanonicalImageProps,
  CanonicalImageResponsive,
  CanonicalImageStyle,
  ImageAlignment,
  ImageCaptionPosition,
  ImageGradientBorderType,
  ImageHoverEffect,
  ImageObjectFit,
  ImageProps,
  ImageShape,
  ImageShadow,
  ImageViewModel,
} from './types'

export const imageContract = {
  defaultProps: defaultImageProps,
  schema: {
    title: 'Image',
    categories: [
      { id: 'content', label: 'Content', expanded: true },
      { id: 'layout', label: 'Layout', expanded: false },
      { id: 'style', label: 'Style', expanded: false },
      { id: 'overlay', label: 'Overlay', expanded: false },
      { id: 'interaction', label: 'Interaction', expanded: false },
      { id: 'advanced', label: 'Advanced', expanded: false },
    ],
    properties: {
      src: { type: 'image', label: 'Image URL', default: defaultImageProps.src, category: 'Content' },
      alt: { type: 'text', label: 'Alt Text', default: defaultImageProps.alt, category: 'Content' },
      linkUrl: { type: 'text', label: 'Link URL', default: defaultImageProps.linkUrl, category: 'Content' },
      openInNewTab: { type: 'toggle', label: 'Open in New Tab', default: defaultImageProps.openInNewTab, category: 'Content' },
      caption: { type: 'text', label: 'Caption', default: defaultImageProps.caption, category: 'Content' },
      captionPosition: {
        type: 'select',
        label: 'Caption Position',
        default: defaultImageProps.captionPosition,
        options: [
          { value: 'bottom', label: 'Bottom' },
          { value: 'top', label: 'Top' },
          { value: 'overlay', label: 'Overlay' },
        ],
        category: 'Content',
      },
      captionAlignment: {
        type: 'select',
        label: 'Caption Alignment',
        default: defaultImageProps.captionAlignment,
        options: [
          { value: 'left', label: 'Left' },
          { value: 'center', label: 'Center' },
          { value: 'right', label: 'Right' },
        ],
        category: 'Content',
      },
      width: { type: 'text', label: 'Width', default: defaultImageProps.width, category: 'Layout' },
      height: { type: 'text', label: 'Height', default: defaultImageProps.height, category: 'Layout' },
      maxWidth: { type: 'text', label: 'Max Width', default: defaultImageProps.maxWidth, category: 'Layout' },
      maxHeight: { type: 'text', label: 'Max Height', default: defaultImageProps.maxHeight, category: 'Layout' },
      objectFit: {
        type: 'select',
        label: 'Object Fit',
        default: defaultImageProps.objectFit,
        options: [
          { value: 'cover', label: 'Cover' },
          { value: 'contain', label: 'Contain' },
          { value: 'fill', label: 'Fill' },
          { value: 'none', label: 'None' },
          { value: 'scale-down', label: 'Scale Down' },
        ],
        category: 'Style',
      },
      objectPosition: { type: 'text', label: 'Object Position', default: defaultImageProps.objectPosition, category: 'Layout' },
      imageZoom: { type: 'number', label: 'Image Zoom', default: defaultImageProps.imageZoom, min: 0.1, max: 3, step: 0.1, category: 'Layout' },
      alignment: {
        type: 'select',
        label: 'Alignment',
        default: defaultImageProps.alignment,
        options: [
          { value: 'left', label: 'Left' },
          { value: 'center', label: 'Center' },
          { value: 'right', label: 'Right' },
        ],
        category: 'Layout',
      },
      componentPositionX: { type: 'text', label: 'Horizontal Position', default: defaultImageProps.componentPositionX, category: 'Layout' },
      componentPositionY: { type: 'text', label: 'Vertical Position', default: defaultImageProps.componentPositionY, category: 'Layout' },
      margin: { type: 'text', label: 'Margin', default: defaultImageProps.margin, category: 'Layout' },
      padding: { type: 'text', label: 'Padding', default: defaultImageProps.padding, category: 'Layout' },
      border: { type: 'text', label: 'Border', default: defaultImageProps.border, category: 'Style' },
      borderRadius: { type: 'text', label: 'Border Radius', default: String(defaultImageProps.borderRadius), category: 'Style' },
      shape: {
        type: 'select',
        label: 'Shape',
        default: defaultImageProps.shape,
        options: [
          { value: 'default', label: 'Default' },
          { value: 'circle', label: 'Circle' },
          { value: 'rounded', label: 'Rounded' },
          { value: 'square', label: 'Square' },
          { value: 'hexagon', label: 'Hexagon' },
          { value: 'diamond', label: 'Diamond' },
          { value: 'star', label: 'Star' },
          { value: 'heart', label: 'Heart' },
          { value: 'parallelogram', label: 'Parallelogram' },
          { value: 'triangle', label: 'Triangle' },
          { value: 'blob', label: 'Blob' },
          { value: 'speech-bubble', label: 'Speech Bubble' },
          { value: 'cross', label: 'Cross' },
          { value: 'custom', label: 'Custom' },
        ],
        category: 'Style',
      },
      customShape: { type: 'text', label: 'Custom Shape', default: defaultImageProps.customShape, category: 'Style' },
      showGradientBorder: { type: 'toggle', label: 'Gradient Border', default: defaultImageProps.showGradientBorder, category: 'Style' },
      gradientBorderColors: { type: 'text', label: 'Border Colors', default: defaultImageProps.gradientBorderColors, category: 'Style' },
      gradientBorderDirection: { type: 'text', label: 'Border Direction', default: defaultImageProps.gradientBorderDirection, category: 'Style' },
      gradientBorderWidth: { type: 'text', label: 'Border Width', default: defaultImageProps.gradientBorderWidth, category: 'Style' },
      gradientBorderType: {
        type: 'select',
        label: 'Border Type',
        default: defaultImageProps.gradientBorderType,
        options: [
          { value: 'linear', label: 'Linear' },
          { value: 'radial', label: 'Radial' },
          { value: 'conic', label: 'Conic' },
        ],
        category: 'Style',
      },
      shadow: { type: 'select', label: 'Shadow', default: defaultImageProps.shadow, options: ['none', 'sm', 'md', 'lg', 'xl'], category: 'Style' },
      showOverlay: { type: 'toggle', label: 'Show Overlay', default: defaultImageProps.showOverlay, category: 'Overlay' },
      overlayColor: { type: 'color', label: 'Overlay Color', default: defaultImageProps.overlayColor, category: 'Overlay' },
      overlayOpacity: { type: 'number', label: 'Overlay Opacity', default: defaultImageProps.overlayOpacity, min: 0, max: 1, step: 0.05, category: 'Overlay' },
      overlayText: { type: 'text', label: 'Overlay Text', default: defaultImageProps.overlayText, category: 'Overlay' },
      hoverEffect: {
        type: 'select',
        label: 'Hover Effect',
        default: defaultImageProps.hoverEffect,
        options: [
          { value: 'none', label: 'None' },
          { value: 'zoom', label: 'Zoom' },
          { value: 'fade', label: 'Fade' },
          { value: 'grayscale', label: 'Grayscale' },
          { value: 'brighten', label: 'Brighten' },
          { value: 'blur', label: 'Blur' },
          { value: 'rotate', label: 'Rotate' },
          { value: 'flip', label: 'Flip' },
        ],
        category: 'Interaction',
      },
      hoverZoom: { type: 'number', label: 'Hover Zoom', default: defaultImageProps.hoverZoom, min: 1, max: 2, step: 0.05, category: 'Interaction' },
      hoverBrightness: { type: 'number', label: 'Hover Brightness', default: defaultImageProps.hoverBrightness, min: 1, max: 2, step: 0.05, category: 'Interaction' },
      hoverDuration: { type: 'number', label: 'Hover Duration', default: defaultImageProps.hoverDuration, min: 0.1, max: 2, step: 0.1, category: 'Interaction' },
      filter: { type: 'text', label: 'Filter', default: defaultImageProps.filter, category: 'Interaction' },
      lazyLoad: { type: 'toggle', label: 'Lazy Load', default: defaultImageProps.lazyLoad, category: 'Advanced' },
      showLightbox: { type: 'toggle', label: 'Enable Lightbox', default: defaultImageProps.showLightbox, category: 'Advanced' },
      className: { type: 'text', label: 'CSS Class', default: defaultImageProps.className, category: 'Advanced' },
      customId: { type: 'text', label: 'Custom ID', default: defaultImageProps.customId, category: 'Advanced' },
    },
  },
  normalize: normalizeImage,
  createViewModel: createImageViewModel,
}
