import { defaultAdvancedParagraphProps } from './defaults'
import { normalizeAdvancedParagraph } from './normalize'
import { createAdvancedParagraphViewModel } from './viewModel'

export type {
  AdvancedParagraph,
  AdvancedParagraphAlignment,
  AdvancedParagraphAriaGroup,
  AdvancedParagraphContentGroup,
  AdvancedParagraphFontStyle,
  AdvancedParagraphInput,
  AdvancedParagraphInteractionGroup,
  AdvancedParagraphLayoutGroup,
  AdvancedParagraphMeta,
  AdvancedParagraphStyleGroup,
  AdvancedParagraphTextDecoration,
  AdvancedParagraphTextTransform,
  AdvancedParagraphType,
  AdvancedParagraphViewModel,
} from './types'

export { defaultAdvancedParagraphProps } from './defaults'
export { normalizeAdvancedParagraph } from './normalize'
export { createAdvancedParagraphViewModel } from './viewModel'

export const advancedParagraphContract = {
  defaultProps: defaultAdvancedParagraphProps,
  schema: {
    title: 'Advanced Paragraph',
    categories: [
      { id: 'base', label: 'Base', expanded: true },
      { id: 'style', label: 'Style', expanded: false },
      { id: 'layout', label: 'Layout', expanded: false },
      { id: 'interaction', label: 'Interaction', expanded: false },
      { id: 'aria', label: 'ARIA', expanded: false },
    ],
    properties: {
      text: { type: 'richtext', label: 'Paragraph Text', default: defaultAdvancedParagraphProps.content.text, category: 'Base' },
      enableRichText: { type: 'toggle', label: 'Enable Rich Text', default: defaultAdvancedParagraphProps.aria.enableRichText, category: 'Base' },
      allowedFormats: {
        type: 'text',
        label: 'Allowed Formats',
        default: defaultAdvancedParagraphProps.aria.allowedFormats.join(', '),
        category: 'Base',
        description: 'Comma-separated rich text formats such as bold, italic, underline, color',
      },
      fontSize: { type: 'text', label: 'Font Size', default: defaultAdvancedParagraphProps.style.fontSize, category: 'Style' },
      fontWeight: { type: 'text', label: 'Font Weight', default: defaultAdvancedParagraphProps.style.fontWeight, category: 'Style' },
      fontFamily: { type: 'text', label: 'Font Family', default: defaultAdvancedParagraphProps.style.fontFamily, category: 'Style' },
      lineHeight: { type: 'text', label: 'Line Height', default: defaultAdvancedParagraphProps.style.lineHeight, category: 'Style' },
      letterSpacing: { type: 'text', label: 'Letter Spacing', default: defaultAdvancedParagraphProps.style.letterSpacing, category: 'Style' },
      textTransform: {
        type: 'select',
        label: 'Text Transform',
        default: defaultAdvancedParagraphProps.style.textTransform,
        options: [
          { value: 'none', label: 'None' },
          { value: 'uppercase', label: 'Uppercase' },
          { value: 'lowercase', label: 'Lowercase' },
          { value: 'capitalize', label: 'Capitalize' },
        ],
        category: 'Style',
      },
      textDecoration: {
        type: 'select',
        label: 'Text Decoration',
        default: defaultAdvancedParagraphProps.style.textDecoration,
        options: [
          { value: 'none', label: 'None' },
          { value: 'underline', label: 'Underline' },
          { value: 'line-through', label: 'Line Through' },
          { value: 'overline', label: 'Overline' },
        ],
        category: 'Style',
      },
      fontStyle: {
        type: 'select',
        label: 'Font Style',
        default: defaultAdvancedParagraphProps.style.fontStyle,
        options: [
          { value: 'normal', label: 'Normal' },
          { value: 'italic', label: 'Italic' },
          { value: 'oblique', label: 'Oblique' },
        ],
        category: 'Style',
      },
      textColor: { type: 'color', label: 'Text Color', default: defaultAdvancedParagraphProps.style.color, category: 'Style' },
      backgroundColor: { type: 'color', label: 'Background Color', default: defaultAdvancedParagraphProps.style.backgroundColor, category: 'Style' },
      border: { type: 'text', label: 'Border', default: defaultAdvancedParagraphProps.style.border, category: 'Style' },
      borderRadius: { type: 'text', label: 'Border Radius', default: defaultAdvancedParagraphProps.style.borderRadius, category: 'Style' },
      borderColor: { type: 'color', label: 'Border Color', default: defaultAdvancedParagraphProps.style.borderColor, category: 'Style' },
      textShadow: { type: 'text', label: 'Text Shadow', default: defaultAdvancedParagraphProps.style.textShadow, category: 'Style' },
      boxShadow: { type: 'text', label: 'Box Shadow', default: defaultAdvancedParagraphProps.style.boxShadow, category: 'Style' },
      opacity: { type: 'number', label: 'Opacity', default: defaultAdvancedParagraphProps.style.opacity, min: 0, max: 1, step: 0.1, category: 'Style' },
      alignment: {
        type: 'select',
        label: 'Alignment',
        default: defaultAdvancedParagraphProps.layout.alignment,
        options: [
          { value: 'left', label: 'Left' },
          { value: 'center', label: 'Center' },
          { value: 'right', label: 'Right' },
          { value: 'justify', label: 'Justify' },
        ],
        category: 'Layout',
      },
      margin: { type: 'text', label: 'Margin', default: defaultAdvancedParagraphProps.style.margin, category: 'Layout' },
      padding: { type: 'text', label: 'Padding', default: defaultAdvancedParagraphProps.style.padding, category: 'Layout' },
      width: { type: 'text', label: 'Width', default: defaultAdvancedParagraphProps.style.width, category: 'Layout' },
      maxWidth: { type: 'text', label: 'Max Width', default: defaultAdvancedParagraphProps.style.maxWidth, category: 'Layout' },
      minHeight: { type: 'text', label: 'Min Height', default: defaultAdvancedParagraphProps.style.minHeight, category: 'Layout' },
      display: {
        type: 'select',
        label: 'Display',
        default: defaultAdvancedParagraphProps.style.display,
        options: [
          { value: 'block', label: 'Block' },
          { value: 'inline', label: 'Inline' },
          { value: 'inline-block', label: 'Inline Block' },
          { value: 'none', label: 'None' },
        ],
        category: 'Layout',
      },
      hoverEffect: {
        type: 'select',
        label: 'Hover Effect',
        default: defaultAdvancedParagraphProps.interaction.hover.effect,
        options: [
          { value: 'none', label: 'None' },
          { value: 'underline', label: 'Underline' },
          { value: 'color-change', label: 'Color Change' },
          { value: 'background-change', label: 'Background Change' },
        ],
        category: 'Interaction',
      },
      hoverTextColor: { type: 'color', label: 'Hover Text Color', default: defaultAdvancedParagraphProps.interaction.hover.color, category: 'Interaction' },
      hoverBackgroundColor: { type: 'color', label: 'Hover Background Color', default: defaultAdvancedParagraphProps.interaction.hover.backgroundColor, category: 'Interaction' },
      transition: { type: 'text', label: 'Transition', default: defaultAdvancedParagraphProps.style.transition, category: 'Interaction' },
      ariaLabel: { type: 'text', label: 'ARIA Label', default: defaultAdvancedParagraphProps.aria.ariaLabel, category: 'ARIA' },
      role: { type: 'text', label: 'Role', default: defaultAdvancedParagraphProps.aria.role, category: 'ARIA' },
      tabIndex: { type: 'number', label: 'Tab Index', default: defaultAdvancedParagraphProps.aria.tabIndex, category: 'ARIA' },
      className: { type: 'text', label: 'CSS Class', default: defaultAdvancedParagraphProps.aria.className, category: 'ARIA' },
      customId: { type: 'text', label: 'Custom ID', default: defaultAdvancedParagraphProps.aria.customId, category: 'ARIA' },
      selectable: { type: 'toggle', label: 'Selectable', default: defaultAdvancedParagraphProps.aria.selectable, category: 'ARIA' },
      editable: { type: 'toggle', label: 'Editable', default: defaultAdvancedParagraphProps.aria.editable, category: 'ARIA' },
      truncate: { type: 'toggle', label: 'Truncate', default: defaultAdvancedParagraphProps.aria.truncate, category: 'ARIA' },
      maxLines: { type: 'number', label: 'Max Lines', default: 0, min: 0, max: 12, category: 'ARIA' },
      visible: { type: 'toggle', label: 'Visible', default: defaultAdvancedParagraphProps.aria.visible, category: 'ARIA' },
      componentId: { type: 'text', label: 'Component ID', default: defaultAdvancedParagraphProps.aria.componentId, category: 'ARIA' },
    },
  },
  normalize: normalizeAdvancedParagraph,
  createViewModel: createAdvancedParagraphViewModel,
}
