import type { FilterOption, FilterProps } from './types'

export const filterDefaultOptions: FilterOption[] = [
  { value: 'option-1', label: 'Option 1' },
  { value: 'option-2', label: 'Option 2' },
  { value: 'option-3', label: 'Option 3' },
]

export const sortDefaultOptions: FilterOption[] = [
  { value: 'popular', label: 'Most popular' },
  { value: 'newest', label: 'Newest first' },
  { value: 'oldest', label: 'Oldest first' },
]

export const tagDefaultOptions: FilterOption[] = [
  { value: 'hot', label: 'Hot', badge: 'Hot' },
  { value: 'warm', label: 'Warm' },
  { value: 'cold', label: 'Cold' },
]

export const checkboxDefaultOptions: FilterOption[] = [
  { value: 'featured', label: 'Featured' },
  { value: 'published', label: 'Published' },
  { value: 'draft', label: 'Draft' },
]

export const radioDefaultOptions: FilterOption[] = [
  { value: 'grid', label: 'Grid view' },
  { value: 'card', label: 'Card view' },
  { value: 'list', label: 'List view' },
]

export const manualDefaultOptions: FilterOption[] = [
  { value: 'all', label: 'All' },
  { value: 'new', label: 'New' },
  { value: 'popular', label: 'Popular' },
]

export const filterDefaultProps: FilterProps = {
  filterType: 'dropdown',
  filterKey: 'filter',
  label: 'Filter',
  helpText: '',
  placeholder: 'Select option...',
  defaultValue: '',
  defaultChecked: false,
  disabled: false,
  required: false,
  clearable: true,
  searchable: false,
  showLabel: true,
  showClearButton: true,
  className: '',
  wrapperClassName: '',
  options: filterDefaultOptions,
  sourceType: 'manual',
  presetKey: 'industry',
  apiEndpoint: '',
  apiMethod: 'GET',
  apiLabelField: 'label',
  apiValueField: 'value',
  closeMenuOnSelect: true,
  maxSelections: 3,
  showSelectedCount: true,
  inline: false,
  columns: 1,
  selectAllEnabled: true,
  selectAllLabel: 'Select all',
  radioStyle: 'default',
  onLabel: 'On',
  offLabel: 'Off',
  toggleColor: '#111827',
  showStateLabel: true,
  defaultSort: 'popular',
  sortField: 'createdAt',
  sortDirection: 'desc',
  removable: true,
  chipStyle: 'pill',
  chipVariant: 'default',
  allowMultiple: true,
  min: 0,
  max: 100,
  step: 1,
  value: '',
  rangeMode: 'single',
  showTooltip: true,
  showTicks: false,
  prefix: '',
  suffix: '',
  showMinMaxLabels: true,
  debounceMs: 250,
  autoFocus: false,
  persistState: false,
  storageKey: '',
  syncWithUrl: false,
  queryParam: 'filter',
  autoApply: true,
  applyButtonLabel: 'Apply',
  resetOnChange: false,
  emitEventName: '',
  dependsOn: '',
  visibleWhen: '',
  disabledWhen: '',
  reloadOptionsOnDependencyChange: false,
  variant: 'default',
  size: 'md',
  density: 'comfortable',
  fullWidth: false,
  labelPosition: 'top',
  orientation: 'vertical',
  mobileVariant: 'stacked',
  desktopVariant: 'inline',
  sticky: false,
  collapsedByDefault: false,
  showDivider: false,
  sectionTitle: '',
  id: '',
  ariaLabel: '',
  ariaDescription: '',
  tabIndex: 0,
  previewMode: false,
}
