import type { FlexboxProps } from './types'

export const defaultFlexboxProps: FlexboxProps = {
  version: 1,
  direction: 'row',
  justifyContent: 'flex-start',
  alignItems: 'stretch',
  alignContent: 'stretch',
  gap: '16px',
  rowGap: '16px',
  columnGap: '16px',
  wrap: 'nowrap',
  padding: '16px',
  minHeight: 'auto',
  backgroundColor: '#ffffff',
  stackOnMobile: true,
  directionMobile: 'column',
  mobileGap: '12px',
  borderRadius: '0px',
  border: 'none',
  shadow: 'none',
  width: '100%',
  maxWidth: 'none',
  preset: 'custom',
  className: '',
  children: [],
}
